name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: gain-dev-tools
  RUN_REGION: us-central1
  SERVICE_NAME: game-of-life-service

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GAIN_DEV_TOOLS_GOOGLE_CREDENTIALS}}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID
      # Build and push image to Google Container Registry
      - name: Build
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --allow-unauthenticated \
            --platform managed
